### PR TITLE
Upgrade to bonsoir_platform_interface 2.0.0

### PR DESCRIPTION
**Pull request by julianscheel**
Updates to be compatible with the latest (2.0.0) `bonsoir_platform_interface` release.

### CODE REVIEW

**Comment by Piero512** [comment]
Hi, this looks like it would probably work fine, but is there a way you can make the linter happy, otherwise, i'll look into this in the weekend.

**Comment by julianscheel** [comment]
Thanks @Piero512, would you mind publishing a release to pub.dev?

**Comment by Piero512** [comment]
Yes, will do. This probably requires a breaking change.

**Comment by Piero512** [comment]
[Done!](https://pub.dev/packages/bonsoir_linux_dbus/versions/0.2.0)

**Comment by julianscheel** [comment]
Thanks :+1:

**Pull request merged**
